### PR TITLE
Use more intelligent environment variable resolution

### LINKED ISSUE #97: Using Fish shell on OSX breaks plugin initialization
The OSX PATH fix (#74) assumes the user's login shell is Bash. If the user's shell is Fish, the PATH interpreting will fail because the output from `printf` will be shell specific and may not be formatted predictably (e.g. separated by `os.pathsep`). This can prevent GoTools from locating the `go` binary and basically breaks the plugin.

@ferbivore proposed a fix (https://github.com/ironcladlou/GoTools/issues/94#issuecomment-138706827) which invokes `sh` from the user's shell, which seems workable.

### PR DESCRIPTION
**Pull request by ironcladlou**
Use smarter environment variable lookups. The new method should be portable across all shells (e.g. fish). Additionally, PATH, GOPATH, and GOROOT are all available for tool lookups and passthrough to tool execution environments.

These changes are also portable across Linux and OSX.

Fixes #97.
Supercedes #98.

### CODE REVIEW

**Comment by ironcladlou** [comment]
/cc @ferbivore @stevekuznetsov 

This needs extensive testing.

**Comment by ferbivore** [comment]
Formatting works (tested on Windows, OS X with fish and OS X with bash), but trying to build pops this error up on OS X:

```
[Errno 2] No such file or directory: 'go'
[cmd: ['go', 'install']]
[dir: /Users/Ferb/Documents/Go/src/github.com/ferbivore/luabox]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

This is because formatting is done through a ToolRunner, but building is done through `window.run_command`. A minor change to `gotools_build.py`, line 87, takes care of that - though you should of course scan through the codebase for any other misplaced instances of `run_command`.

```python
#self.window.run_command("exec", exec_opts)
self.runner.run("go", ["install"] + build_packages)
```

Also, for some reason, I get the four DEBUG messages (gopath, goroot, ospath, gorootbin) every time I press a key, which is probably not a good thing.

**Comment by ironcladlou** [comment]
Good catch, I'll sweep for that sort of thing next time I can work on this. I wonder if the output-per-keypress is related to the completion engine. I believe that by default, ST will start autocompletion after 50ms of inactivity, and GoTools hooks into the autocomplete engine with a class which will load settings each time. I should probably open a bug to eliminate that sort of frequent settings reload.

**Comment by ironcladlou** [comment]
https://github.com/ironcladlou/GoTools/commit/5e91167e60e33e7333bb148e100586b59edc212d should fix builds/tests and also adds GOROOT and PATH to the build/test execution environment.

**Comment by ironcladlou** [comment]
I'll remove all the debugging output when it's closer to stable.

**Comment by ironcladlou** [comment]
Merging this to master to start weeding out bugs. I'm going to try and refactor the settings mechanism to use settings events for efficiency.

**Pull request merged**
