### PR TITLE
(Probably) fix initialization on OS X

### PR DESCRIPTION
**Pull request by ferbivore**
Fix tested with fish and bash as login shells, and with Sublime Text launched from both .app folder and `subl`. Additionally, fixes a bug where `subprocess.Popen(...).communicate()` always returns None for stderr.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Sorry, I needed to merge #92 and introduced conflicts. I'm looking at this code again in the context of my latest refactoring, and am starting to wonder if it would make sense to use the `sh` call for all non-Windows platforms. We could establish an order of precedence for PATH, GOPATH, and GOROOT like `subl settings > login shell env > go env > subl env`.

What do you think?

**Comment by ironcladlou** [comment]
Maybe `subl settings > login shell env > subl env > go env`... my thinking is that any paths explicitly set by the user (OS or shell level) should take precedence over whatever `go env` resolves.

**Comment by ironcladlou** [comment]
I've been playing with the new precedence idea in [my own branch](https://github.com/ironcladlou/GoTools/compare/smarter-env-lookups) which incorporates many of your ideas. I'm running into an oddity that I now remember encountering when I was messing with the `printf` fix.

Check out [this gist](https://gist.githubusercontent.com/ironcladlou/5b54099c87f05346e412/raw/e0da055b37b51140f3e66b1c0ec2453b59cb1c6f/gistfile1.txt) with the debugging output I added.

I (like many) have a custom bash prompt which uses colors and stuff. If the code creates a login shell, the var values end up tainted with escape codes. I'm not yet sure how to avoid this, and somehow it seems to generally work for me regardless on Darwin (but maybe by some coincidence- I use GoTools on Linux day to day and haven't run through as many path related scenarios on OSX until just now for this testing.)

**Comment by ferbivore** [comment]
[SublimeFixMacPath](
https://github.com/int3h/SublimeFixMacPath/blob/master/FixPath.py) does
this to get rid of escape codes:

```python
# Remove ANSI control characters (see:
http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed
)
sysPathString = re.sub(r'\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]', '',
sysPathString)
```

They also set `TERM=ansi` and `CLICOLOR=""`, for what it's worth.

**Comment by ferbivore** [comment]
[SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath/blob/master/FixPath.py)
does this to get rid of escape codes:

```python
# Remove ANSI control characters (see:
http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed
)
sysPathString = re.sub(r'\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]', '',
sysPathString)
```

They also set `TERM=ansi` and `CLICOLOR=""`, for what it's worth.

**Comment by ferbivore** [comment]
What you're doing in your branch seems like a good idea, although you have a bit of a naming confusion with `OSPATH`. It works fine for me (in Windows, at least - will test OS X later) with a minor change to the `GoToolsSettings` constructor:

```python
self.ospath = self.GoEnv["OSPATH"] # before
self.ospath = self.GoEnv["PATH"]   # after
```

**Comment by ferbivore** [comment]
Tested on OS X just now, and it doesn't run `go env` with the  GOROOT/GOPATH variables my shell sets. Adding this to `load_goenv` just before the "gather up the Go environment" section does the trick:

```python
# Set environment variables
os.environ["GOPATH"] = env["GOPATH"]
os.environ["GOROOT"] = env["GOROOT"]
```

**Comment by ironcladlou** [comment]
I should have mentioned the branch is totally incomplete- there's more work to do beyond load_goenv- I wouldn't bother testing yet. I stopped prototyping once I hit the control char issue.

**Comment by ironcladlou** [comment]
Been toiling over this all morning and can't find a way to strip these ANSI codes. No regex I've found works, and I've tried a variety of hacks inside the shell itself (unsetting PROMPT_COMMAND, PS1, etc).

**Comment by ferbivore** [comment]
Try `r'\x1b.*\\'`, it seems to work for the PATH, GOPATH and (empty) GOROOT you have in the gist.

**Comment by ironcladlou** [comment]
I'll try that later, thanks.

I wish I understood the origin of the garbage. In my case, I have a PROMPT_COMMAND specified in my bashrc which sets history stuff and a colorful PS1. I don't understand why prompt-like output would be appearing to begin with. I also read that ANSI codes emitted from the actual command being executed shouldn't be present when the output of the command is piped (which isn't totally relevant here since echo isn't emitting color).

Do you have any insight into the underlying source of the control chars? I just can't understand why sourcing profile/bashrc which sets PROMPT_COMMAND and/or PS1 would have any effect here when the shell's non-interactive.

**Comment by ferbivore** [comment]
Could you upload your profile and bashrc?

**Comment by ironcladlou** [comment]
The profile sources bashrc, and here's the relevant part: https://gist.github.com/ironcladlou/b9e031bb8a34ed7c4b91

My overriding concern is that stripping stuff is brittle. I'd much rather prevent the control chars from being output in the first place, if possible.

If this gets too difficult I might just have to introduce settings keys for these things.

**Comment by ferbivore** [comment]
Sadly, I can't reproduce it on any of my systems. No idea what's going on - as you said, the PROMPT_COMMAND shouldn't do anything in a non-interactive shell.

**Comment by ironcladlou** [comment]
I'm sure that I saw the code in master work sometimes (no chars) and not others when I originally coded it, and decided there was some weirdness specific to my setup. Guess I'll have to keep digging.

**Comment by ironcladlou** [comment]
I thought of a solution. Huge hack. :joy:

**Comment by ironcladlou** [comment]
Teaser:

```python
cmd = [os.getenv("SHELL"), "-l", "-c", "sh -c -l 'echo ${0}>{1}'".format(k, tempf.name)]
```

**Pull request closed without merging**
