### PR TITLE
Please give me internet points

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Comment by ironcladlou** [comment]
lol.

Unfortunately for your stats, Sublime doesn't have a "test" system, so my original text is accurate. You may appeal this decision.

**Comment by stevekuznetsov** [comment]
Fair enough. That reads really weird. I'll think about this ground-changing fix.

**Comment by pmorie** [comment]
@stevekuznetsov I admire the direct tone of this PR

**Comment by stevekuznetsov** [comment]
@pmorie Thanks. Last time I was a little more subtle and got called out.

**Comment by ironcladlou** [comment]
url

**Pull request closed without merging**
