### PR TITLE
fix oracle implements invocation

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@ironcladlou near as i can tell this is necessary for the implements resolution to work.

**Comment by ironcladlou** [comment]
What are you doing up at 3AM, young man?

Do you have some example where implements is borked without package scope?

**Comment by bparees** [comment]
i'm in brno.  so 9am :)

output w/o this fix:
```
GoTools: DEBUG: spawning process...
GoTools: DEBUG: 	command:     /home/bparees/git/gocode/bin/oracle -pos=/home/bparees/git/gocode/src/github.com/openshift/origin/pkg/generate/app/dockerimagelookup.go:#407 -format=plain implements
GoTools: DEBUG: 	environment: {'USER': 'bparees', 'OS': '/home/bparees/git/gocode/src/github.com/openshift', 'SKIP_SQUASH': '1', 'XDG_SESSION_ID': '1', 'HISTSIZE': '1000', 'JAVA_HOME': '/etc/alternatives/java_sdk', 'MATE_DESKTOP_SESSION_ID': 'this-is-deprecated', 'CONSOLE_PATH': '../../origin-server/console', 'TERM': 'xterm-256color', 'XDG_SESSION_TYPE': 'x11', 'XDG_VTNR': '2', 'GPG_AGENT_INFO': '/run/user/1006/keyring/gpg:0:1', 'DESKTOP_SESSION': 'mate', 'SHLVL': '2', 'COLORTERM': 'mate-terminal', 'HOME': '/home/bparees', 'SSH_AUTH_SOCK': '/run/user/1006/keyring/ssh', 'USERNAME': 'bparees', 'QTDIR': '/usr/lib64/qt-3.3', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-ljKthRNO2v,guid=d47add5240562c43daededa4560af1b9', 'LOGNAME': 'bparees', 'XDG_SEAT': 'seat0', 'SSH_AGENT_PID': '1854', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:', 'DISPLAY': ':0', 'GDMSESSION': 'mate', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'PS1': '\\W$(__git_ps1)$ ', 'PWD': '/home/bparees/git/gocode/src/github.com/openshift', 'QTINC': '/usr/lib64/qt-3.3/include', 'GOPATH': '/home/bparees/git/gocode/src/github.com/openshift/origin/Godeps/_workspace:/home/bparees/git/gocode', 'OLDPWD': '/home/bparees', 'XAUTHORITY': '/run/user/1006/gdm/Xauthority', 'PATH': '/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/bparees/.local/bin:/home/bparees/bin:/home/bparees/scripts:/bin:/home/bparees/.opam/system/bin:/home/bparees/git/gocode/src/github.com/openshift/origin/_output/etcd/bin:/home/bparees/git/gocode/src/github.com/openshift/origin/_output/local/bin/linux/amd64::/home/bparees/git/gocode/src/github.com/openshift/source-to-image/_output/local/go/bin:/home/bparees/git/gocode/bin:/home/bparees/.local/bin:/home/bparees/bin:/home/bparees/scripts:/bin:/home/bparees/.opam/system/bin:/home/bparees/git/gocode/src/github.com/openshift/origin/_output/etcd/bin:/home/bparees/git/gocode/src/github.com/openshift/origin/_output/local/bin/linux/amd64::/home/bparees/git/gocode/src/github.com/openshift/source-to-image/_output/local/go/bin:/home/bparees/git/gocode/bin:/home/bparees/.local/bin:/home/bparees/bin:/home/bparees/scripts:/bin:/home/bparees/.opam/system/bin:/home/bparees/git/gocode/src/github.com/openshift/origin/_output/etcd/bin:/home/bparees/git/gocode/src/github.com/openshift/origin/_output/local/bin/linux/amd64::/home/bparees/git/gocode/src/github.com/openshift/source-to-image/_output/local/go/bin:/home/bparees/git/gocode/bin', 'CVS_RSH': 'ssh', 'WINDOWPATH': '2', 'KDE_IS_PRELINKED': '1', 'SHELL': '/bin/bash', 'CONSOLE_CONFIG_FILE': '/home/bparees/.openshift/console.conf', 'GOROOT': '/usr/lib/golang', 'MAIL': '/var/spool/mail/bparees', 'XDG_SESSION_DESKTOP': 'mate', 'XDG_CURRENT_DESKTOP': 'MATE', 'KDEDIRS': '/usr', 'GDM_LANG': 'en_US.UTF-8', 'LESSOPEN': '|/usr/bin/lesspipe.sh %s', 'HISTCONTROL': 'ignoredups', '_': '/usr/bin/nohup', 'LANG': 'en_US.UTF-8', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/1843,unix/unix:/tmp/.ICE-unix/1843', 'HOSTNAME': 'bparees.rh', 'WINDOWID': '25165855', 'XDG_RUNTIME_DIR': '/run/user/1006'}
GoTools: DEBUG: process returned (2) in 0 seconds
GoTools: DEBUG: stderr:
oracle: no package arguments.
Run 'oracle -help' for more information.

GoTools: DEBUG: oracle implements output: 
```

note the "no package arguments" error at the end.

implements never works for me w/o this change.

**Comment by ironcladlou** [comment]
Pointer analysis scope isn't actually required in oracle (according to the manual, and for all versions I've ever used). However, it seems that for some strange/old version of oracle (@bparees cites golang-googlecode-tools-oracle-0-2.0.hga7e14835e46b.fc22.x86_64) the command is requiring a scope.

According to our tests, adding the package scope, while apparently unnecessary, doesn't seem to break newer version of oracle. So, let's merge this for backwards compatibility.

**Pull request merged**
