### PR TITLE
added a 'both' option for format command backend

### LINKED ISSUE #84: Support running both goimports and gofmt on save
The `goimports` tool is not equivalent to `gofmt` for formatting (see https://github.com/golang/go/issues/8759). Users who want to use `goimports` but also want the formatting/simplification provided by `gofmt` have no means with GoTools.

The `format_backend` setting could support a `both` value which would cause the output of `goimports` to be fed immediately to `gofmt` before replacing the buffer.

### PR DESCRIPTION
**Pull request by stevekuznetsov**
@ironcladlou 
Fixes #84

### CODE REVIEW

**Comment by ironcladlou** [comment]
Thanks! Can you also add a little more detail to the config comment and also update the readme to describe more precisely what "both" will do?

**Comment by stevekuznetsov** [comment]
@ironcladlou Updated the doc

**Comment by tamird** [comment]
:+1: this would be awesome.

On a side note, this project is terrific. You should add the word "golang" to the description so that it's easier to find on https://packagecontrol.io/.

**Comment by ironcladlou** [comment]
Thanks for the feedback. I'll see if I can make the project more discoverable with the description tweak you suggested.

**Comment by ironcladlou** [comment]
@stevekuznetsov 

I sanity checked this locally and while it works as advertised, I noticed some unseemly main UI thread blocking when using `both` or `goimports` (`goimports` is the culprit). I think the next thing that'll need done after this merge will be to

1. Refactor `GotoolsFormat#run` to deduplicate the tool execution stuff and,
2. Make the formatting operations asynchronous.

I'm going to go ahead and merge this to master but I'm going to try and address 1 and 2 before tagging a new release for package control.

**Pull request merged**
