### PR TITLE
Add gorename integration

### LINKED ISSUE #91: Add support for gorename
Got GoTools installed with painless setup. Thanks!

I'm curious if you have plans to add support for `gorename`, or if you'd accept a PR for this.

### PR DESCRIPTION
**Pull request by cbednarski**
Closes #91

### CODE REVIEW

**Comment by ironcladlou** [comment]
Thanks for the PR. I'll take some time this evening to do a more in depth review and some testing.

**Comment by cbednarski** [comment]
Sounds good! I haven't tested on Windows or Linux yet but it's working on OSX using the official go installer. I think it will require some config to work with a homebrew installation since that goes into `/usr/local/Cellar/` instead of `/usr/local/go/`.

**Comment by ironcladlou** [comment]
I normally develop and test on Linux, but will be sure to focus on OSX when I get to this later. The PATH hack seems to work for me (and apparently for the original reporter in #73). Since GoTools is working for you in general, I assume the hack is effective on your end? If the hack's still good, we shouldn't need a new `path` setting. One of my goals is minimize the amount of settings by using conventions/lookups/inference of intent wherever possible.

**Comment by ironcladlou** [comment]
(P.S., I use the Homebrew go installation)

**Comment by cbednarski** [comment]
I'll see if there is a standard path for go homebrew. I can add both at the same time and it will use whichever one it finds first.

**Comment by cbednarski** [comment]
I'll also check out the path hack you mentioned.have not had a chance to follow up in detail on the other comments.

**Comment by ironcladlou** [comment]
Sorry, I didn't have time to get to this last night after all. Will try again today.

**Comment by ironcladlou** [comment]
Just to let you know, I haven't forgotten about this one. I've got a branch off your branch locally in which I'm doing some cleanup and testing, and will have something pushed for review very soon.

P.S., I had no idea about python's string `format` method: THANK YOU.

**Comment by ironcladlou** [comment]
@cbednarski I made a [pull request](https://github.com/cbednarski/GoTools/pull/2) to your fork with some refactoring and enhancements to your support. I haven't had a chance to test on OSX yet.

**Comment by cbednarski** [comment]
@ironcladlou Thanks for the update. I tested this on OSX using the [go pkg installer](http://golang.org/dl/), and it works!

**Comment by ironcladlou** [comment]
Great... I'll be able to test it with Homebrew a bit later.

While testing rename with just one file, I was getting perceptible UI blocking. We consider making this asynchronous, especially since cursor restoration isn't an issue (#86 has more details on the complications.)

Check `gotools_oracle.py` for an example which should be directly applicable.

(P.S., I'm not a Python programmer, so feel free to refactor stuff to be more idiomatic as you come across it)

**Comment by ironcladlou** [comment]
I haven't had a lot of luck with the Sublime Text status line for long running operations. Getting text to display is fine, but most of the time it gets overwritten by other messages sooner than I'd like. I'm not sure what other strategies are available for letting users see the progress of commands outside of the Sublime  console.

**Comment by cbednarski** [comment]
Ah yeah it's kinda slow. :\ I'll take a look sometime this week. I think we could do something similar to the search dialog which is also a long-running operation.

**Comment by ironcladlou** [comment]
>Ah yeah it's kinda slow. :\ I'll take a look sometime this week. I think we could do something similar to the search dialog which is also a long-running operation.

Hmm... open a "live" buffer tab with the output?

**Comment by ironcladlou** [comment]
Created another PR to your fork to make the command async: https://github.com/cbednarski/GoTools/pull/3

**Comment by ironcladlou** [comment]
@cbednarski could you test the current branch a little more? If you think it's working okay, squash these commits and let's get it into master.

**Comment by ironcladlou** [comment]
cc @stevekuznetsov - you might be interested in testing this as well.

**Comment by ironcladlou** [comment]
I'm merging this to let it bake for a while.

**Comment by ironcladlou** [comment]
Oops- I should have squashed that first. Oh well!

**Comment by cbednarski** [comment]
Thanks! I'll check this out from master and let you know if I run into anything weird.

**Comment by stevekuznetsov** [comment]
+100 for this addition

**Pull request merged**
